package hugo.ifnmg.bookstore.repository;

import hugo.ifnmg.bookstore.entity.Entity;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Implementation of general operations and definition of specific operations
 * for <i>Data Access Object</i>.
 *
 * @param <E>: Entity.
 * @param <K>: Key.
 */
public abstract class DataAcessObject<E, K> implements IDataAcessObject<E, K> {
    @Override
    public K saveOrUpdate(E e) {
        Long ID = 0L;
        if (((Entity) e).getID() == null || ((Entity) e).getID() == 0) {
            try (
                PreparedStatement pst = DBConnection.getConnection()
                        .prepareStatement(getInsertStatement(), Statement.RETURN_GENERATED_KEYS);
            ) {
                buildStatement(pst, e);
                pst.executeUpdate();
                ResultSet rst = pst.getGeneratedKeys();
                if (rst.next())
                    ID = rst.getLong(1);
            } catch (SQLException ex) {
                System.out.println(">> Exception: " + ex);
            }
        } else {
            try (
                PreparedStatement pst = DBConnection.getConnection()
                        .prepareStatement(getUpdateStatement());
                ) {
                    buildStatement(pst, e);
                    pst.executeUpdate();
                    ID = ((Entity) e).getID();
            } catch (SQLException ex) {
                System.out.println(">> Exception: " + ex);
            }
        }
        return (K) ID;
    }

    @Override
    public E getByID(K ID) {
        try (
            PreparedStatement pst= DBConnection.getConnection()
                    .prepareStatement(getSelectStatementByID());
        ) {
            pst.setLong(1, (Long) ID);
            ResultSet rst = pst.executeQuery();
            if (rst.next())
                return buildEntity(rst);
        } catch (SQLException ex) {
            System.out.println(">> Exception: " + ex);
        }
        return null;
    }

    @Override
    public List<E> getAll() {
        ArrayList<E> entities = new ArrayList<>();

        try (
            PreparedStatement pst = DBConnection.getConnection()
                    .prepareStatement(getSelectStatementAll());
        ) {
            ResultSet rst = pst.executeQuery();
            while (rst.next())
                entities.add(buildEntity(rst));
        } catch (SQLException ex) {
            System.out.println(">> Exception: " + ex);
        }
        
        if (entities.isEmpty())
            return null;
        return entities;
    }
    
    @Override
    public Boolean delete(K ID) {
        if ((Long) ID != 0 && (Long) ID != null) {
            try (
                PreparedStatement pst = DBConnection.getConnection()
                        .prepareStatement(getDeleteStatementByID());
            ) {
                pst.setLong(1, (Long) ID);
                pst.executeUpdate();
            } catch (SQLException ex) {
                System.out.println(">> Exception: " + ex);
            }
        }
        return true;
    }
    
    /**
     * SQL Insert Statement for each type of Entity.
     * 
     * @return A string with the SQL Insert Statement.
     */
    public abstract String getInsertStatement();

    /**
     * SQL Update Statement for each type of Entity.
     *
     * @return A string with the SQL Update statement.
     */
    public abstract String getUpdateStatement();

    /**
     * SQL Select Statement by ID for each type of Entity.
     *
     * @return A string with the SQL Select Statement by ID.
     */
    public abstract String getSelectStatementByID();

    /**
     * SQL Select Statement for each type of Entity.
     * 
     * @return A string with the SQL Select Statement.
     */
    public abstract String getSelectStatementAll();
    
    /**
     * SQL Delete Statement for each type of Entity.
     * 
     * @return A string with the SQL Delete Statement.
     */
    public abstract String getDeleteStatementByID();
    
    /**
     * Build the SQL statement with the values contained in the received
     * object of an Entity.
     *
     * @param pst Query to be prepared.
     * @param e Object with values to be embedded in the query.
     */
    public abstract void buildStatement(PreparedStatement pst, E e);
    
    
    /**
     * Extracts an object from the result generated by the query.
     *
     * @param rst Record retrieved from database.
     * @return Object equivalent to the received record.
     */
    public abstract E buildEntity(ResultSet rst);
}
